### ISSUE TITLE
CyHeif seems to auto rotate on load, which will case issues saving with exif

### ISSUE THREAD

**Issue by cdgriffith** [ram-nat/CyHeif#1]
First off, thanks for the great wrapper that actually works on Windows! Wasn't able to get pyheif working even with their new pull request for Windows. 

Example image with exif rotation attached: [example_heif_with_exif_orientation.zip](https://github.com/ram-nat/CyHeif/files/8100626/example_heif_with_exif_orientation.zip)

Usually PIL does not auto-rotate images on load, so you have to use the `ImageOps.exif_transpose(pil_img)` transform. 

CyHeif seems to auto-rotate it? Which causes a problem with the `run.py` example when also saving the same `exif` data without removing the Orientation from it, or else the output will be incorrectly rotated. 

Edit: Even weirder, if saved as PNG without same exif, rotation is wrong?

So for example to convert it to both, one has to have the exif and one can't: 

```python
from pathlib import Path
import sys

from PIL import Image
from cyheifloader import cyheif

incoming = Path(sys.argv[1]).absolute()
output_path = incoming.parent / f"{incoming.stem}_converted"
pil_img = cyheif.get_pil_image(str(incoming).encode(encoding="utf-8"))

pil_img.save(f"{output_path}.jpg", quality=95)
pil_img.save(f{output_path}.png", exif=pil_img.getexif().tobytes())
```

**Comment by ram-nat** [comment]
Thanks for filing the issue. I am a novice at details of both pillow images and HEIC format. From my brief testing, the issue seems to be that the exif that we get from the HEIC states orientation, the loaded HEIC image is already rotated to the stated orientation and the exif=pil_img.getexif().tobytes() in the pillow image save call then causes the orientation to be applied again to the jpg by display programs causing the incorrect rotation (you can check this by commenting out that part and see that the saved jpg is no longer rotated). I tried setting the apply_transformations flag to False during the HEIC load to see if this will prevent the loaded HEIC image from having the orientation rotated but that doesn't seem to be working. Will update if I come up with a good way to handle this scenario.

**Comment by ram-nat** [comment]
Seems to be an underlying issue with libheif and images that have both transform and exif orientation specified - https://github.com/strukturag/libheif/issues/227
